<a href="https://colab.research.google.com/github/baibhav7992-star/baibhav7992-star/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name:Baibhav kumar

Roll No.:Betn1ai25098


In [ ]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [13]:
# Create required arrays here
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


# 1D array of 10 integers
array_1d = [i for i in range(1, 11)]

# 3x3 matrix
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix[1][2])




# Identity matrix of size 4
identity_matrix = np.eye(4)
print("Identity Matrix (4x4)\n:")
print(identity_matrix)

# Random 5x5 matrix
random_matrix = np.random.randint(0, 10, (5, 5))
print("Random 5x5 Matrix\n:")
print(random_matrix)


6
Identity Matrix (4x4)
:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random 5x5 Matrix
:
[[0 0 7 9 6]
 [3 5 7 1 6]
 [0 2 6 9 4]
 [4 3 9 1 5]
 [3 9 6 6 3]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [19]:
A = np.arange(1, 26).reshape(5,5)
print(A)

# Extract 2nd row
second_row = A[1, :]
print(second_row)

# Extract 3rd column
third_column = A[:, 2]
print(third_column)

# Extract 2x2 center matrix
center_submatrix = A[2:3, 2:3]
print(center_submatrix)

# Reverse last row
reversed_last_row = A[-1, ::-1]
print(reversed_last_row)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 6  7  8  9 10]
[ 3  8 13 18 23]
[[13]]
[25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [23]:
# Perform broadcasting operations here
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

# Add scalar 10 to matrix
A_plus_10 = A + 10
print("Matrix after adding scalar 10:\n", A_plus_10, "\n")

# Add vector [1,2,3,4,5] to each row
import numpy as np

# Original matrix
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

# Define the vector
vector = np.array([1, 2, 3, 4, 5])

# Add vector to each row using broadcasting
A_plus_vector = A + vector

print("Matrix after adding vector to each row:\n", A_plus_vector, "\n")

# Normalize matrix between 0 and 1
A_min = A_plus_vector.min()
A_max = A_plus_vector.max()
A_normalized = (A_plus_vector - A_min) / (A_max - A_min)
print("Normalized matrix between 0 and 1:\n", A_normalized)




Matrix after adding scalar 10:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

Matrix after adding vector to each row:
 [[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]] 

Normalized matrix between 0 and 1:
 [[0.         0.11111111 0.22222222 0.33333333 0.44444444]
 [0.27777778 0.38888889 0.5        0.61111111 0.72222222]
 [0.55555556 0.66666667 0.77777778 0.88888889 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [22]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication
elementwise = X * Y
print("Element-wise multiplication:", elementwise)
# Dot product
dot_product = np.dot(X, Y)
print("Dot product:", dot_product)

# Mean and Standard Deviation
mean_X = np.mean(X)
std_X = np.std(X)
print("Mean of X:", mean_X)
print("Standard Deviation of X:", std_X)



Element-wise multiplication: [ 5 12 21 32]
Dot product: 70
Mean of X: 2.5
Standard Deviation of X: 1.118033988749895


Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [24]:
marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
import numpy as np
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
print("Total per student:", total)
print("Average per student:", average)

Total per student: [245 218 272 195 250]
Average per student: [81.66666667 72.66666667 90.66666667 65.         83.33333333]
